#+title: Doom emacs Config
#+PROPERTY: header-args :tangle config.el :results none
#+options: toc:2

* Table of Contents :toc:
- [[#doom-default-configuration][Doom Default configuration]]
- [[#general-configuration][General configuration]]
  - [[#variables][Variables]]
  - [[#functions][Functions]]
  - [[#keyboard][Keyboard]]
- [[#visuals][Visuals]]
  - [[#maximize-frame-and-remove-decorations][Maximize frame and remove decorations]]
  - [[#customize-splash-screen][Customize splash screen]]
  - [[#modeline-font-size][Modeline font size]]
  - [[#show-battery-and-hour][Show battery and hour]]
  - [[#popups][Popups]]
- [[#language][Language]]
  - [[#variables-1][Variables]]
  - [[#functions-1][Functions]]
  - [[#keyboard-1][Keyboard]]
- [[#org][ORG]]
  - [[#variables-2][Variables]]
  - [[#functions-2][Functions]]
  - [[#keyboard-2][Keyboard]]
  - [[#org-functionality][Org functionality]]

* Doom Default configuration
Standard configuration of Doom Emacs

#+begin_src emacs-lisp
;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-

;; Place your private configuration here! Remember, you do not need to run 'doom
;; sync' after modifying this file!


;; Some functionality uses this to identify you, e.g. GPG configuration, email
;; clients, file templates and snippets.
(setq user-full-name "R.P."
      user-mail-address "")

;; Doom exposes five (optional) variables for controlling fonts in Doom. Here
;; are the three important ones:
;;
;; + `doom-font'
;; + `doom-variable-pitch-font'
;; + `doom-big-font' -- used for `doom-big-font-mode'; use this for
;;   presentations or streaming.
;;
;; They all accept either a font-spec, font string ("Input Mono-12"), or xlfd
;; font string. You generally only need these two:
(setq doom-font (font-spec :family "Blex Mono Nerd Font" :size 17) ;; :weight 'regular)
      doom-variable-pitch-font (font-spec :family "IBM Plex Sans" :size 19 :weight 'light))

;; There are two ways to load a theme. Both assume the theme is installed and
;; available. You can either set `doom-theme' or manually load a theme with the
;; `load-theme' function. This is the default:
(setq doom-theme 'doom-gruvbox)

;; If you use `org' and don't want your org files in the default location below,
;; change `org-directory'. It must be set before org loads!
(setq org-directory "~/Documenti/emacs/org/")

;; This determines the style of line numbers in effect. If set to `nil', line
;; numbers are disabled. For relative line numbers, set this to `relative'.
(setq display-line-numbers-type t)


;; Here are some additional functions/macros that could help you configure Doom:
;;
;; - `load!' for loading external *.el files relative to this one
;; - `use-package!' for configuring packages
;; - `after!' for running code after a package has loaded
;; - `add-load-path!' for adding directories to the `load-path', relative to
;;   this file. Emacs searches the `load-path' when you load packages with
;;   `require' or `use-package'.
;; - `map!' for binding new keys
;;
;; To get information about any of these functions/macros, move the cursor over
;; the highlighted symbol at press 'K' (non-evil users must press 'C-c c k').
;; This will open documentation for it, including demos of how they are used.
;;
;; You can also try 'gd' (or 'C-c c d') to jump to their definition and see how
;; they are implemented.

#+end_src

* General configuration
** Variables
*** Evil-search wrap
When executing macros they stop at the end of the file.

#+begin_src emacs-lisp
(setq evil-search-wrap 'nil)
#+end_src

*** Clipboard like vim

#+begin_src emacs-lisp
(setq select-enable-clipboard nil)
#+end_src

*** Add startpage search engine for search online

#+begin_src emacs-lisp
(add-to-list '+lookup-provider-url-alist '("Startpage" "https://www.startpage.com/sp/search?query=%s"))
#+end_src

*** Turn off ws-butler-mode

#+begin_src emacs-lisp
(remove-hook 'doom-first-buffer-hook #'ws-butler-global-mode)
#+end_src

*** Template di python

#+begin_src emacs-lisp
(set-file-template! "/__\\.py$g" :trigger "__" :mode 'python-mode)
#+end_src

*** Dired hide hidden files

From [[https://qerub.se/hiding-hidden-files-in-emacs-dired][here]] and [[https://stackoverflow.com/questions/31363541/how-to-map-emacs-evil-keys-to-dired-plus][here]].

#+begin_src emacs-lisp 
(setq dired-omit-files "^\\...+$")

(eval-after-load 'dired
  '(evil-define-key 'normal dired-mode-map
     (kbd ")") 'dired-omit-mode))
#+end_src

** Functions
*** Q to execute line in shell

From [[https://emacs.stackexchange.com/questions/55506/run-current-line-or-selection-in-shell-then-insert-result-in-emacs-buffer-acme][here]].
This function exectutes the line in shell and puts the output under the line
with the command. Repeating the command updates the output.

#+begin_src emacs-lisp
(defun robert/execute-in-shell-and-put-in-buffer (b e)
  "Run current line as shell code and insert/update output."
  (interactive (list (line-beginning-position)
                     (line-end-position)))
  (save-excursion
    ;; delete old output
    (delete-region
     (progn (forward-line) (point))
     (progn (while (get-text-property (point) '$$)
              (forward-line))
            (point)))

    (unless (bolp) (insert "\n"))
    (let* ((command (buffer-substring-no-properties b e))
           (output (with-temp-buffer
                     (shell-command command t t)
                     (buffer-string)))
           (start (point)))
      (insert (propertize output '$$ t 'rear-nonsticky t))
      (pulse-momentary-highlight-region start (point)))))

(define-key evil-normal-state-map (kbd "Q") 'robert/execute-in-shell-and-put-in-buffer)
#+end_src

*** Show diff before close file
From [[https://emacs.stackexchange.com/questions/3245/kill-buffer-prompt-with-option-to-diff-the-changes/3363#3363][here]]. Code from 2014.

#+begin_src emacs-lisp 
(defun robert/kill-current-buffer ()
  (interactive)
  (catch 'quit
    (save-window-excursion
      (let (done)
        (when (and buffer-file-name (buffer-modified-p))
          (while (not done)
            (let ((response (read-char-choice
                             (format "Save file %s? (y, n, d, q) " (buffer-file-name))
                             '(?y ?n ?d ?q))))
              (setq done (cond
                          ((eq response ?q) (throw 'quit nil))
                          ((eq response ?y) (save-buffer) t)
                          ((eq response ?n) (set-buffer-modified-p nil) t)
                          ((eq response ?d) (diff-buffer-with-file) nil))))))
        (kill-buffer (current-buffer))))))
(map! :leader :desc "Kill buffer" "b k" #'robert/kill-current-buffer)
(map! :leader :desc "Kill buffer" "b d" #'kill-buffer-and-window)
#+end_src


#+begin_src emacs-lisp :tangle no
;; This works only when `kill-buffer' is called, does nothing in ibuffer idk
;; Removed because gives error "error in process sentinel selecting deleted buffer"
;; when calling `org-agenda-file-to-front' 
;; (defun robert/kill-buffer (orig-func &optional buffer-or-name)
;;   (catch 'quit
;;     (save-window-excursion
;;       (with-current-buffer buffer-or-name
;;         (let (done (buf (current-buffer)))
;;           (when (and buffer-file-name (buffer-modified-p))
;;             (while (not done)
;;               (let ((response (read-char-choice
;;                                (format "Save file %s? (y, n, d, q) " (buffer-file-name buf))
;;                                '(?y ?n ?d ?q))))
;;                 (setq done (cond
;;                             ((eq response ?q) (throw 'quit nil))
;;                             ((eq response ?y) (save-buffer) t)
;;                             ((eq response ?n) (set-buffer-modified-p nil) t)
;;                             ((eq response ?d) (diff-buffer-with-file) nil))))))
;;           (apply orig-func (list (current-buffer))))))))

;; (advice-add 'kill-buffer :around #'robert/kill-buffer)
#+end_src

*** Open directory in external file manager

#+begin_src emacs-lisp
(defun open-file-externally ()
  "Open the current file's directory in external file browser."
  (interactive)
  (if (equal major-mode 'dired-mode)
      (consult-file-externally (dired-copy-filename-as-kill))
      (browse-url (expand-file-name default-directory))))

(map! :leader :desc "Browse or open externally" "o x" #'open-file-externally)

;; (remove-hook! 'dired-mode-hook #'dired-omit-mode)
#+end_src

*** Dired split

Dired split window corresponding to current file directory.

#+begin_src emacs-lisp
(defun robert/dired-popup-this-location ()
  "Open popup dired buffer of current file"
  (interactive)
  (dired-other-window default-directory))

(map! :leader :desc "Explore this dir" "x" #'robert/dired-popup-this-location)
#+end_src

** Keyboard 
*** Remove SPC-SPC shortcut

#+begin_src emacs-lisp
(map! :leader "SPC" nil)
#+end_src

*** Remove SPC-X shortcut

#+begin_src emacs-lisp
(map! :leader "X" nil)
#+end_src

*** Toggle smart parens mode and disable on startup

#+begin_src emacs-lisp
(map! :leader "t [" #'smartparens-mode)
(remove-hook 'doom-first-buffer-hook #'smartparens-global-mode)
#+end_src

*** Map menu key to save

#+begin_src emacs-lisp
(global-set-key (kbd "<menu>") 'save-buffer)
#+end_src

*** C-e vim shortcut
Aggiunge la scorciatoia per copiare quello che è sotto

#+begin_src emacs-lisp
(define-key evil-insert-state-map (kbd "\C-e") 'evil-copy-from-below)
#+end_src

*** Switch +vterm/toggle and +vterm/here

#+begin_src emacs-lisp
(map! :leader :desc "Open vterm popup" "o T" #'+vterm/toggle)
(map! :leader :desc "Open vterm here" "o t" #'+vterm/here)
#+end_src

*** Ctrl+ins, Shift+ins always system clipboard
#+begin_src emacs-lisp
(global-set-key (kbd "S-<insert>") 'clipboard-yank)
(define-key evil-visual-state-map (kbd "C-<insert>") 'robert/copy)
(define-key evil-visual-state-map (kbd "S-<deltechar>") 'clipboard-kill-region)

(defun robert/copy ()
  "Copy to system clipboard"
  (interactive)
  (evil-use-register ?+)
  (call-interactively 'evil-yank))
(global-set-key (kbd "C-<insert>") 'robert/copy)
#+end_src

*** Grep

#+begin_src emacs-lisp
(map! :leader :desc "Grep" "/" #'grep)
#+end_src

* Visuals
** Maximize frame and remove decorations

From [[https://emacs.stackexchange.com/questions/2999/how-to-maximize-my-emacs-frame-on-start-up][here]].

#+begin_src emacs-lisp
(add-to-list 'initial-frame-alist '(fullscreen . maximized))
(add-to-list 'default-frame-alist '(undecorated . t))
#+end_src

** Customize splash screen

From [[https://discourse.doomemacs.org/t/how-to-change-your-splash-screen/57][discourse]].

This is the ascii splash image.

#+begin_src emacs-lisp :tangle no
(defun my-weebery-is-always-greater ()
  (let* ((banner '("█▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀█"
                   "█░░╦─╦╔╗╦─╔╗╔╗╔╦╗╔╗░░█"
                   "█░░║║║╠─║─║─║║║║║╠─░░█"
                   "█░░╚╩╝╚╝╚╝╚╝╚╝╩─╩╚╝░░█"
                   "█▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄█"))
         (longest-line (apply #'max (mapcar #'length banner))))
    (put-text-property
     (point)
     (dolist (line banner (point))
       (insert (+doom-dashboard--center
                +doom-dashboard--width
                (concat line (make-string (max 0 (- longest-line (length line))) 32)))
               "\n"))
     'face 'doom-dashboard-banner)))

(setq +doom-dashboard-ascii-banner-fn #'my-weebery-is-always-greater)
#+end_src

This is the image splash image for the GUI.

#+begin_src emacs-lisp
(setq fancy-splash-image "~/Pictures/.emacs_mars.png")

(assoc-delete-all "Reload last session" +doom-dashboard-menu-sections)
(assoc-delete-all "Open org-agenda" +doom-dashboard-menu-sections)
(assoc-delete-all "Open project" +doom-dashboard-menu-sections)
(assoc-delete-all "Open documentation" +doom-dashboard-menu-sections)

(remove-hook! '+doom-dashboard-functions #'doom-dashboard-widget-footer)

(add-hook! '+doom-dashboard-functions :append
  (insert "\n" (+doom-dashboard--center +doom-dashboard--width "I showed you my config files, pls respond")))
#+end_src

** Modeline font size

The font size is actually fine, the icons are too big.

#+begin_src emacs-lisp :tangle no
(custom-set-faces!
  '(mode-line :family "IBM Plex Mono" :height 1.0)
  '(mode-line-inactive :family "IBM Plex Mono" :height 1.0))
#+end_src

#+begin_src emacs-lisp
(setq all-the-icons-scale-factor 1.0)
#+end_src

** Show battery and hour

#+begin_src emacs-lisp
(add-hook 'after-init-hook #'display-battery-mode)
(add-hook 'after-init-hook #'display-time)
;; (add-hook 'after-init-hook #'menu-bar-mode)
(setq 
 display-time-format "%a·%d/%m/%y·%H:%M"
 ;; display-time-24hr-format t
 ;; display-time-day-and-date t
 display-time-default-load-average 3)

#+end_src

** Popups

From [[https://docs.doomemacs.org/latest/modules/ui/popup/][here]].
By default, the mode-line is hidden in popups. To disable this, you can either:
Change the default :modeline property in +popup-defaults: 

#+begin_src emacs-lisp :tangle no
;;(plist-put +popup-defaults :modeline t)
#+end_src

Completely disable management of the mode-line in popups: 

#+begin_src emacs-lisp
(remove-hook '+popup-buffer-mode-hook #'+popup-set-modeline-on-enable-h)
#+end_src

* Language
** Variables
*** Translation

#+begin_src emacs-lisp
(setq gts-translate-list '(("it" "en")
                           ("en" "it")
                           ("it" "es")
                           ("es" "it")))

(after! go-translate
  (setq gts-default-translator
        (gts-translator
         :picker (gts-prompt-picker)
         :engines (list (gts-bing-engine) (gts-google-engine))
         :render (gts-buffer-render))))
#+end_src

*** Disable company popup on startup

#+begin_src emacs-lisp
(setq company-idle-delay nil)
#+end_src

*** Front-end company-box

Useful when in variable pitch mode.

#+begin_src emacs-lisp
(add-hook 'company-mode-hook 'company-box-mode)
#+end_src

** Functions
*** Function that switches between two dictionaries

#+begin_src emacs-lisp
(after! ispell
  (ispell-change-dictionary "italian"))

(defun fd-switch-dictionary()
 (interactive)
 (let* ((dic ispell-current-dictionary)
        (change (if (string= dic "italian") "english" "italian")))
  (ispell-change-dictionary change)
  (message "Dictionary switched from %s to %s" dic change)))

(map! :leader :desc "Switch dictionary" "t d" #'fd-switch-dictionary)
#+end_src

** Keyboard

*** Flyspell
Rimuove la scorciatoia di default per la correzione automatica e ne aggiunge un'altra con g.

#+begin_src emacs-lisp
(eval-after-load "flyspell"
  '(define-key flyspell-mode-map (kbd "C-M-i") nil))
(global-set-key (kbd "<M-tab>") 'complete-symbol)
(define-key evil-normal-state-map (kbd "g .") 'flyspell-auto-correct-word)
#+end_src

* ORG
** Variables
*** Hooks org-mode

#+begin_src emacs-lisp
(add-hook 'org-mode-hook 'mixed-pitch-mode)
(add-hook 'org-mode-hook '+org-pretty-mode)
(add-hook 'org-mode-hook '(lambda () (text-scale-increase +1)))
(add-hook 'org-mode-hook '(lambda () (modify-syntax-entry ?\' " ")))
#+end_src

*** Org-ellipses

#+begin_src emacs-lisp
(setq org-ellipses " ^ ")
#+end_src

** Functions
*** Occur Buffer for tree view of org mode headers

From the [[https://www.emacswiki.org/emacs/OccurMode#h5o-7][Emacs Wiki]]

This gets rid of the line numbers and the header line, so that the result
is more like the output from ‘grep’. You might want to bind this to C-c C-x.

Then use =doom/window-maximize-buffer= to hide the occur buffer.

Unable to delete the header line (*number* matches for *match* in buffer: *buffer*).
Text is read only.
The occur buffer will be renamed with the name of the buffer from which the
occur command was called. 

#+begin_src emacs-lisp 
(defun occur-mode-clean-buffer ()
  "Removes all commentary from the *Occur* buffer, leaving the
 unadorned lines."
  (interactive)
  (if (get-buffer "*Occur*")
      (save-excursion
        (set-buffer (get-buffer "*Occur*"))
        (goto-char (point-min))
        (read-only-mode 0)
        ;; (if (looking-at "^[0-9]+ lines matching \"")
        ;;     (kill-line 1))
        ;; (flush-lines "^[0-9]+ matches for")
        (while (re-search-forward "^[ \t]*[0-9]+:"
                                  (point-max)
                                  t)
          (replace-match "")
          (forward-line 1))
        (+evil/window-move-left) 
        (evil-window-increase-width 28)
        ;; (+popup-mode)
        (+word-wrap-mode)
        (text-scale-adjust -1)
        ;; (rename-buffer (concat "*" buff-name "-Occur*"))
        (occur-rename-buffer nil t)
        (read-only-mode 1))
    (message "There is no buffer named \"*Occur*\".")))
;; (add-hook 'occur-hook #'occur-mode-clean-buffer)
#+end_src

#+begin_src emacs-lisp
(defun robert/occur-tree-org ()
  "Show headings of org file"
  (interactive)
  (occur "^\*+ ")
  (occur-mode-clean-buffer))

(map! :after org
      :map org-mode-map
      :localleader
      :desc "Show Org tree" ";" #'robert/occur-tree-org)
#+end_src

Test of toggle function
#+begin_src emacs-lisp :tangle no
(defun robert/toggle-org-occur-tree ()
  "Toggle the side panel of occur in org mode"
  (interactive)
  (let ((occur-buffer-name (concat "*Occur: " (buffer-name) "*" ))
    ;;if, cond"-Occur*"
    (if (get-buffer occur-buffer-name)
        ;;then
        (with-current-buffer occur-buffer-name
         
         ) ()))))
#+end_src

*** Screenshot insertion from screenshot folder

From [[https://old.reddit.com/r/emacs/comments/52q70g/paste_an_image_on_clipboard_to_emacs_org_mode/][reddit]]. 
I have a shell script to create screenshots with =xfce4-screenshooter= to select
a region and assign a name in a specific path.
Hours wasted for this thing: 10.

#+begin_src emacs-lisp :tangle no
(defun get-newest-file-from-dir  (path)
  "Get latest file (including directory) in PATH."
  (car (directory-files path 'full nil #'file-newer-than-file-p)))
#+end_src

#+begin_src emacs-lisp 
(defun aj-fetch-latest (path)
  (let ((e (f-entries path)))
    (car (sort e (lambda (a b)
                   (not (time-less-p (aj-mtime a)
                                     (aj-mtime b))))))))
(defun aj-mtime (f) (let ((attrs (file-attributes f))) (nth 5 attrs)))

(defun insert-org-image--time-dependent ()
  "Moves image from screenshot folder to `buffer-file-name'_media, inserting org-mode link"
  (interactive)
  (let* (
         ;; (indir (expand-file-name ~/Documenti/emacs/screenshots))
         (infile (aj-fetch-latest "~/Documenti/emacs/screenshots"))
         ;; (infile (get-newest-file-from-dir "~/Documenti/emacs/screenshots"))
         (outdir (concat (buffer-file-name) "_media"))
         (outfile (expand-file-name (file-name-nondirectory infile) outdir)))
    (unless (file-directory-p outdir)
      (make-directory outdir t))
    (when (or
           (string-equal "0" (format-time-string "%-M" 
                                                 (time-since (f-modification-time infile))))
           (string-equal "1" (format-time-string "%-M" 
                                                 (time-since (f-modification-time infile)))))
      (rename-file infile outfile)
      (insert (concat (concat 
                       "[[./" 
                       (file-name-nondirectory (buffer-file-name)) 
                       "_media/" 
                       (file-name-nondirectory outfile)) 
                      "]]"))))
  (newline)
  (newline))

(defun insert-org-image--time-independent ()
  "Moves image from screenshot folder to `buffer-file-name'_media, inserting org-mode link"
  (interactive)
  (let* (
         ;; (indir (expand-file-name ~/Documenti/emacs/screenshots))
         (infile (aj-fetch-latest "~/Documenti/emacs/screenshots"))
         ;; (infile (get-newest-file-from-dir "~/Documenti/emacs/screenshots"))
         (outdir (concat (buffer-file-name) "_media"))
         (outfile (expand-file-name (file-name-nondirectory infile) outdir)))
    (unless (file-directory-p outdir)
      (make-directory outdir t))
    (rename-file infile outfile)
    (insert (concat (concat 
                     "[[./" 
                     (file-name-nondirectory (buffer-file-name)) 
                     "_media/" 
                     (file-name-nondirectory outfile)) 
                    "]]")))
  (newline)
  (newline))

(map! :after org
      :map org-mode-map
      :localleader
      :desc "Insert screenshot (last 1m)" "a i" #'insert-org-image--time-dependent)
(map! :after org
      :map org-mode-map
      :localleader
      :desc "Insert screenshot" "a I" #'insert-org-image--time-independent)
;; (map! :after org
;;       :map org-mode-map
;;       :localleader
;;       :desc "Insert screenshot" "<print>" #'insert-org-image--time-dependent)
#+end_src

*** Screenshot insertion from within emacs

From [[https://stackoverflow.com/questions/17435995/paste-an-image-on-clipboard-to-emacs-org-mode-file-without-saving-it][here]].
This allows to take a screenshot with import from within emacs. Cannot move cursor, not very useful.
#+begin_src emacs-lisp :tangle no
(defun my-org-screenshot ()
  "Take a screenshot into a time stamped unique-named file in the
same directory as the org-buffer and insert a link to this file."
  (interactive)
  ;; (org-display-inline-images)
  (setq filename
        (concat
         (make-temp-name
          (concat (file-name-nondirectory (buffer-file-name))
                  "_imgs/"
                  (format-time-string "%Y%m%d_%H%M%S_")) ) ".png"))
  (unless (file-exists-p (file-name-directory filename))
    (make-directory (file-name-directory filename)))
  ; take screenshot
  (if (eq system-type 'darwin)
      (call-process "screencapture" nil nil nil "-i" filename))
  (if (eq system-type 'gnu/linux)
      (call-process "import" nil nil nil filename))
  ; insert into file if correctly taken
  (if (file-exists-p filename)
    (insert (concat "[[./" filename "]]"))))


#+end_src

** Keyboard
*** Font shortcuts

#+begin_src emacs-lisp
(map! :leader :desc "toggle font mode" "t v" #'mixed-pitch-mode)
(map! :leader :desc "Toggle emphasis markers" "t e" #'+org-pretty-mode)
(map! :leader :desc "Toggle emphasis headings" "t h" #'org-tree-slide-heading-emphasis-toggle)
(map! :leader :desc "Toggle centered window" "t C" #'centered-window-mode)
#+end_src

*** Insert heading on same level

#+begin_src emacs-lisp
(with-eval-after-load "org"
  (define-key org-mode-map (kbd "<C-M-return>") #'org-insert-heading))
#+end_src

** Org functionality
*** Org-tree-slide-mode
**** Custom play/stop hooks
#+begin_src emacs-lisp
(defun robert/org-tree-slide-play-mode-hook ()
  ;; (interactive)
        (+org-pretty-mode)
        (setq display-line-numbers nil))

(defun robert/org-tree-slide-stop-mode-hook ()
  ;; (interactive)
        (+org-pretty-mode)
        (setq display-line-numbers t))

(add-hook 'org-tree-slide-play-hook 'robert/org-tree-slide-play-mode-hook)
(add-hook 'org-tree-slide-stop-hook 'robert/org-tree-slide-stop-mode-hook)
#+end_src

**** Advice remove
- Allow to start the presentation where the cursor is
- Remove advice allows to move normally
- Remove hook of default prettify function
- Add hook of custom prettify function

#+begin_src emacs-lisp
(after! org-tree-slide
  (setq org-tree-slide-cursor-init nil)
  (advice-remove 'org-tree-slide--display-tree-with-narrow
                 #'+org-present--hide-first-heading-maybe-a)
  (remove-hook 'org-tree-slide-mode-hook #'+org-present-prettify-slide-h)
  (add-hook 'org-tree-slide-mode-hook #'+org-present-prettify-slide-h-custom))
#+end_src

**** Prettify function without centering
Copy the configuration of the function, comment out the centering
portion

#+begin_src emacs-lisp
(defun +org-present-prettify-slide-h-custom ()
  "Set up the org window for presentation."
  (setq +org-present-text-scale 5)
  (let ((arg (if org-tree-slide-mode +1 -1)))
    (if (not org-tree-slide-mode)
        (when +org-present--last-wconf
          (set-window-configuration +org-present--last-wconf))
      (setq +org-present--last-wconf (current-window-configuration))
      (doom/window-maximize-buffer))
    ;; (when (fboundp 'centered-window-mode)
    ;;   (setq-local cwm-use-vertical-padding t)
    ;;   (setq-local cwm-frame-internal-border 100)
    ;;   (setq-local cwm-left-fringe-ratio -10)
    ;;   (setq-local cwm-centered-window-width 300)
    ;;   (centered-window-mode arg))
    ;; (hide-mode-line-mode arg)
    (+org-pretty-mode arg)
    (cond (org-tree-slide-mode
           (set-window-fringes nil 0 0)
           (when (bound-and-true-p flyspell-mode)
             (flyspell-mode -1))
           (add-hook 'kill-buffer-hook #'+org-present--cleanup-org-tree-slides-mode
                     nil 'local)
           (text-scale-set +org-present-text-scale)
           (ignore-errors (org-latex-preview '(4))))
          (t
           (text-scale-set 0)
           (set-window-fringes nil fringe-mode fringe-mode)
           (org-clear-latex-preview)
           (org-remove-inline-images)
           (org-mode)))
    (redraw-display)))
#+end_src

*** Org-caputre notes templates

#+begin_src emacs-lisp
(after! org
  (setq org-capture-templates
        '(("t" "Todo" plain (file+headline "~/Documenti/emacs/org/capture/task.org" "TODO")
           "- [ ] %?"
           :unnarrowed nil)
          ("j" "Journal" entry (file+datetree "~/Documenti/emacs/org/capture/journal.org")
           "* %?\nEntered on %U\n  %i\n  %a\n\n"
           :unnarrowed nil)
          ("n" "Nota" plain (file "~/Documenti/emacs/org/capture/note.org" )
           "* %?\n  %i\n  %a\n\n"
           :unnarrowed nil))))

#+end_src

*** Org-journal

#+begin_src emacs-lisp
(setq org-journal-date-prefix "#+TITLE: "
      org-journal-time-prefix "* "
      org-journal-date-format "%A, %Y_%m_%d"
      org-journal-file-format "%Y_%m_%d.org")

(map! :leader :desc "Org-J new entry" "J" #'org-journal-new-entry)
#+end_src

*** Org-roam

**** Config

#+begin_src emacs-lisp
(setq org-roam-directory "~/Documenti/emacs/org/roam")

(setq org-roam-capture-templates
      '(("d" "default"
         plain "%?"
         :if-new (file+head "${slug}_%<%Y_%m_%d_%H%m%s>.org" "#+title: ${title}
,#+filetags:
,#+category: ${title}
,#+date: %U\n")
         :unnarrowed t)))

(setq org-roam-dailies-capture-templates
      '(("d" "default"
         entry "* %<%H:%M> %?"
         :target (file+head "%<%Y_%m_%d>.org" "#+title: %<%Y-%m-%d>\n"))))

;;; IDK
;; (setq org-roam-dailies-capture-templates
;;       '(("d" "default"
;;          entry "* %<%H:%M> %?"
;;          :target (file+head "%<%Y_%m_%d>.org" "#+title: %<%Y-%m-%d>\n"))))
#+end_src

**** Keyboard

#+begin_src emacs-lisp
(defun org-roam-node-insert-immediate (arg &rest args)
  (interactive "P")
  (let ((args (cons arg args))
        (org-roam-capture-templates (list (append (car org-roam-capture-templates)
                                                  '(:immediate-finish t)))))
    (apply #'org-roam-node-insert args)))

(map! :leader :desc "Node insert immediate" "n r i" #'org-roam-node-insert-immediate)
(define-key evil-insert-state-map (kbd "C-M-n") 'org-roam-node-insert-immediate)

(map! :leader :desc "Node insert" "n r I" #'org-roam-node-insert)
#+end_src

??? Don't remember
#+begin_src emacs-lisp :tangle no
;; (defun robert/org-roam-filter-by-tag (tag-name)
;;   (lambda (node)
;;     member tag-name (org-roam-node-tags node)))

;; (defun robert/org-roam-list-notes-by-tag (tag-name)
;;   (mapcar #'org-roam-node-file
;;           (seq-filter
;;            (robert/org-roam-filter-by-tag name)
;;            (org-roam-node-list))))
#+end_src

