#!/usr/bin/env python

### Importare le librerie

import math

### Definire le funzioni

#def

### Definire la funzione main

# def main():

### __name__

if __name__ == '__main__':
#    main()
    $1
